### ISSUE TITLE
Second batch of issues

### ISSUE THREAD

**Issue by weijia-cheng** [kingrpaul/algernon-blackwood_short-fiction#2]
Sorry for the delay between the first batch and this one, I’ve been really busy at work lately and looking through such a long commit history was daunting! I’m going to work through this a chunk at a time.

# Spelling

- [x] In `the-egyptian-desert-from-helouan`, you have “diverse and rugged scenery” where the original text reads “diversified and rugged scenery” ([source](https://archive.org/details/sim_country-life_1912-03-16_31_793/page/382/mode/2up?q=divers)).
- [x] In `the-wendigo`, you have “diverse shook their dripping heads” where it should presumably read “divers shook their dripping heads.” This was introduced while modernizing spelling under the old “divers” rule (which has since been removed).
- [x] In `the-tryst`, “rendez-vous” (in a French context) was modernized to “rendezvous,” which should be reverted because the French spelling has a dash ([1](https://en.wiktionary.org/wiki/rendez-vous#French) [2](https://fr.wiktionary.org/wiki/rendez-vous)).
- [x] Revert 78164abdb7b9b104231443f997ef76695dfdf8c9 because [gasthaus](https://www.merriam-webster.com/dictionary/gasthaus) is a Merriam-Webster Unabridged term and we only deitalicize and modernize spelling on non-unabridged dictionary terms. Also, after reverting, make sure all instances are italicized as German.
- [x] I am not sure if I agree with the capitalization changes in 5156f93209d4afe0a7169148de55d61012124638. The use of capitalization seems significant, e.g. just in the first sentence the use of “Dream” versus “dream” sets up the personification used in the second sentence. Though we modernize archaic capitalization, we don’t modernize deliberate literary style choices. We should revert these capitalization changes.
- [x] Revert the “Pole Star” and “Government” changes in 14fdd451d7ceebd9256a296f490fbf2b9746396b since those are both being used as proper nouns.
- [x] In `sand.xhtml`, the word “indescriable” was changed to “indescribable” (“indescriable loneliness,” “indescriable quality of the desert”). I don’t think this is just a typo for indescribable since it’s used twice and an actual word (it would be a form of [descriable](https://www.merriam-webster.com/dictionary/descriable)).

# Semantics

- [x] Sanskrit terms in `sleep-and-how-to-do-without-it` (e.g. “sattva”) should be italicized and with semantics for Sanskrit (`sa-Latn`).

# Commit History

- [x] a1e76f85d13371d54287d794bccc843749534103 mixes a non-editorial typo fix with editorial changes. We need to rebase out the non-editorial typo fix (the missed *ed* in “touched”).
- [x] ffdb4fb50c744e4f297be32a393cdc163f60f04d Your spelling modernization is mixed in with several non-editorial changes. You will need to rebase that out. (Also, it should be “*A*eolian” and not “aeolian.”)
- [x] d68f09751fc843f246a2aa8a2b84864e68ec7c3a mixes non-editorial quotation mark changes with editorial spelling changes.
- [x] bebb663504a147752207b7ea2e4a3574c2526010 mixes non-editorial typo fix (o to 0) with editorial spelling changes.

# Metadata

- [x] You still have `the-price-of-wiggins-orgy.xhtml` (with one *s* instead of two) in `content.opf`, so lint can’t read the file.

**Comment by kingrpaul** [comment]
Indescriable v indescribable.

There are 4 instances of "indescriable" or "indescribable" used in “Sand”. 
1. “ancient, indescribable garments”—Archive agrees with Gutenberg agrees with me, so no issue.
2. “dignity of the little human movements…had become now indescribable”—Archive agrees with Gutenberg agrees with me, so no issue.
3. “That indescri[b]able quality of the Desert”—Archive uses “indescriable” which Gutenberg changes to “indescribable,” recording a transcription note. I retained the Gutenberg revision.
4. “indescriable loneliness was in his heart”—Archive agrees with Gutenberg, but I revised this to “indescribable,” concluding the transcriber had missed it.

So, 3 and 4 are in question. 

Based on the wording of the note, the transcriber did not intend to leave any instance of “indescriable” in the text: ‘Transcriber's Note: In chapter IX of the story Sand, "indescriable" was corrected to "indescribable."’ Blackwood uses no version of “descry” anywhere else that I see.

indescriable: cannot be seen
indescribable: cannot be put into words

#3: Is this quality of the desert seeable? Yes, it’s 'described' as “undisguised” but is ‘described’ only in terms of its effects, because it is indescribable. This is a legit correction on the transcriber’s part. 

#4 Is the man’s loneliness hidden from the man himself? No. It’s declared in a short sentence with no ambiguity. He’s described as searching, but not for this. This was a missed correction on the transcriber’s part.

**Comment by weijia-cheng** [comment]
Ok, let's leave the "indescribable" change for now, then. We can maybe put that in a production note.
